### ISSUE TITLE
quantitative evaluation on DTU dataset

### ISSUE THREAD

**Issue by weihuyixin** [bdwsq1996/Effi-MVS#12]
Hello, thanks for the code. After I reproduce it based on README.md 
Why are the quantitative evaluation results of my DTU dataset wrong?
The results look like: DTU | Acc. (mm) | Comp. (mm) | Overall (mm) | |-----------|------------|--------------| | 0.321 | 0.714 | 0.519 |

**Comment by bdwsq1996** [comment]
> Hello, thanks for the code. After I reproduce it based on README.md Why are the quantitative evaluation results of my DTU dataset wrong? The results look like: DTU | Acc. (mm) | Comp. (mm) | Overall (mm) | |-----------|------------|--------------| | 0.321 | 0.714 | 0.519 |

This issue is caused by using the new version of the DTU dataset.
In the old version of DTU datasets, the last line in the cam.txt is Depth_min, Depth_interval.
In the new version of DTU datasets, the last line in the cam.txt is Depth_min, Depth_max.
My code is suitable for old version of datasets. 

I just updated the code to adapt to the new version of the dataset. Please download the code again and the problem should be resolved.

**Comment by weihuyixin** [comment]
Thank you for your answer. I have solved it.
